server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
zuul:
  prefix: /api
  routes:
    item-service: /item/**